### ISSUE TITLE
Overall review

### ISSUE THREAD

**Issue by LogicX1** [WebAhead5/quickly-find-#11]
I liked the code, its mostly clean, very easy to understand , file structure is also good disregarding the testing which seems to be in progress.
Error handling can be done better for specific stuff like a not found page,but the important part is errors should never crash your website and you got that covered.
For clarity, the website can have a small description or place holder or something to indicate what can and can't be searched.
Web site is responsive and that's cool

**Comment by jrd656** [comment]
Awesome. Thanks for the feedback. We've added that.
